name = "mcp-devkit-server-dev-design"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSIONS"
id = "2f06cd067d794e099fe9dd7a9b2dd22f"

[browser]
binding = "BROWSER"
